---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 026, 8/26/21 10:43 PM
---
if fs.exists('/data/') then
    fs.delete('/data/')
end
os.loadAPI('global/locator')
locator.setLocalCoords(0, 0, 0)
locator.setLocalRotation(0)