---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 003, 9/3/21 11:17 PM
---

function getInventory()
    inv = {}
    for n=1, 16 do
        inv[n] = turtle.getItemDetail(n)
    end
    return inv
end

function contains(name)
    if string.match(name, ":") then
        for n=1, 16 do
            if turtle.getItemDetail(n).name == name then
                return n
            end
        end
    else
        for n=1, 16 do
            if string.sub(turtle.getItemDetail(n).name, -1*string.len(name)) == name then
                return n
            end
        end
    end
    return -1
end