---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 026, 8/26/21 10:27 PM
---

function setLocalCoords(x, y, z)
    local f
    local data
    if not fs.exists('/data/') then
        fs.makeDir('/data')
        data = {}
        data.localCoords = {}
        data.localCoords.x=x
        data.localCoords.y=y
        data.localCoords.z=z
        f = fs.open('/data/local', 'w')
        f.write(textutils.serialize(data))
        f.close()
        return
    end
    f = fs.open('/data/local', 'r')
    data = textutils.unserialize(f.readAll())
    data.localCoords = {}
    data.localCoords.x=x
    data.localCoords.y=y
    data.localCoords.z=z
    f.close()
    f = fs.open('/data/local', 'w')
    f.write(textutils.serialize(data))
    f.close()
end

function getLocalCoords()
    local data
    if fs.exists('/data/local') then
        local f = fs.open('/data/local', 'r')
        data = textutils.unserialize(f.readAll())
        f.close()
    end
    return data.localCoords
end

funcs = {}
funcs['setLocalCoords'] = setLocalCoords
funcs['getLocalCoords'] = getLocalCoords
