---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 026, 8/26/21 10:27 PM
---

function setLocalCoords(x, y, z)
    local f
    local data
    if not fs.exists('/data/') then
        fs.makeDir('/data')
        data = {}
        data.localCoords = {}
        data.localCoords.x=x
        data.localCoords.y=y
        data.localCoords.z=z
        f = fs.open('/data/local', 'w')
        f.write(textutils.serialize(data))
        f.close()
        return
    end
    f = fs.open('/data/local', 'r')
    data = textutils.unserialize(f.readAll())
    data.localCoords = {}
    data.localCoords.x=x
    data.localCoords.y=y
    data.localCoords.z=z
    f.close()
    f = fs.open('/data/local', 'w')
    f.write(textutils.serialize(data))
    f.close()
end

function getLocalCoords()
    local data
    if fs.exists('/data/local') then
        local f = fs.open('/data/local', 'r')
        data = textutils.unserialize(f.readAll())
        f.close()
    end
    return data.localCoords
end

function localMove(x, y, z)
    for i=1, math.abs(x), 1 do
        if x > 0 then turtle.forward() else turtle.back(); end
    end
    turtle.turnRight()
    for i=1, math.abs(y), 1 do
        if y > 0 then turtle.forward() else turtle.back(); end
    end
    turtle.turnLeft()
    for i=1, math.abs(z), 1 do
        if z > 0 then turtle.up() else turtle.down(); end
    end
    coords = getLocalCoords()
    setLocalCoords(coords.x + x, coords.y + y, coords.z + z)
end

funcs = {}
funcs['setLocalCoords'] = setLocalCoords
funcs['getLocalCoords'] = getLocalCoords
