---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 026, 8/26/21 10:49 PM
---
--- usage: timer path/to/api api function number
---
---
args = {...}

print(unpack(args, 5, #args))

os.loadAPI(args[1])
local parse = unpack(args, 5, #args)
fun = _G[args[2]].funcs[args[3]]

t = os.clock()
for x=0, tonumber(args[4]), 1 do
    fun( parse )
end
print(os.clock()-t)