---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 027, 8/27/21 6:09 AM
---

args = {...}
local data = http.get(args[1])
if fs.exists(args[2]) then
    fs.delete(args[2])
end
local f = fs.open(args[2], 'w')
f.write(data.readAll())
data.close()