---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 027, 8/27/21 6:09 AM
---

args = {...}
if fs.exists(args[2]) then
    print('msg: existing file found - deleting')
    fs.delete(args[2])
end
local txt = ''
while txt == '' do
    local data = http.get(args[1])
    txt = data.readAll()
    data.close()
end
print("msg: file created - writing")
local f = fs.open(args[2], 'w')
f.write(txt)
f.close()
print("msg: job done")