---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sasha Harp.
--- DateTime: 004, 9/4/21 12:49 AM
---

os.loadAPI("global/locator")
args = {...}

if args[1] == 'free' then
    locator.moveHome()
else
    print('err: not implemented!')
end